import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CalendarDays, Check, Download, MapPin, Plus, Users, X } from "lucide-react";
import { api } from "../lib/api";
import type { Channel, Guild, GuildEvent, User } from "../types";

export function EventsView({ channel, guild, socket }: { channel: Channel; guild: Guild; currentUser?: User; socket?: { on?: (event: string, listener: (payload: any) => void) => void; off?: (event: string, listener: (payload: any) => void) => void } }) {
  const [events,setEvents]=useState<GuildEvent[]>([]); const [showCreate,setShowCreate]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{ const r=await api<{events:GuildEvent[]}>(`/api/guilds/${guild.id}/events`); setEvents(r.events); },[guild.id]);
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Falha ao carregar eventos"));},[load]);
  useEffect(()=>{
    const refresh=(payload:{guildId?:string})=>{ if(!payload.guildId || payload.guildId===guild.id) void load(); };
    socket?.on?.("event:changed",refresh); socket?.on?.("event:rsvp",refresh);
    return()=>{socket?.off?.("event:changed",refresh);socket?.off?.("event:rsvp",refresh);};
  },[guild.id,load,socket]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await api(`/api/guilds/${guild.id}/events`,{method:"POST",body:JSON.stringify({title:String(f.get("title")||""),description:String(f.get("description")||""),location:String(f.get("location")||""),channelId:channel.id,startsAt:new Date(String(f.get("startsAt"))).toISOString(),endsAt:f.get("endsAt")?new Date(String(f.get("endsAt"))).toISOString():null,capacity:f.get("capacity")?Number(f.get("capacity")):null})});setShowCreate(false);await load();}catch(e){setError(e instanceof Error?e.message:"Nao foi possivel criar o evento");}}
  async function rsvp(id:string,status:"GOING"|"INTERESTED"|"NOT_GOING"){await api(`/api/events/${id}/rsvp`,{method:"POST",body:JSON.stringify({status})});await load();}
  return <section className="feature-view events-view ginga-surface-events"><header className="content-header"><div className="channel-title"><CalendarDays size={19}/><strong>{channel.name}</strong></div><span className="channel-topic">Agenda compartilhada do espaco</span>{guild.permissions.canManageEvents&&<button className="primary-button compact" onClick={()=>setShowCreate(true)}><Plus size={16}/> Novo evento</button>}</header>{error&&<div className="inline-alert danger">{error}</div>}<div className="feature-scroll events-grid">{events.map(item=><article className="event-card" key={item.id}><div className="event-date"><strong>{new Date(item.startsAt).getDate()}</strong><span>{new Date(item.startsAt).toLocaleString("pt-BR",{month:"short"}).toUpperCase()}</span></div><div className="event-copy"><div className="event-kicker"><span className="eyebrow">{new Date(item.startsAt).toLocaleString("pt-BR",{weekday:"long",hour:"2-digit",minute:"2-digit"})}</span><span className={`event-state ${new Date(item.startsAt).getTime() < Date.now() ? "past" : "upcoming"}`}>{new Date(item.startsAt).getTime() < Date.now() ? "ENCERRADO" : "AGENDADO"}</span></div><h3>{item.title}</h3><p>{item.description}</p>{item.location&&<span><MapPin size={14}/> {item.location}</span>}<span><Users size={14}/> {item._count?.rsvps ?? item.rsvps?.length ?? 0} respostas</span><div className="event-actions"><button onClick={()=>void rsvp(item.id,"GOING")}><Check size={14}/> Eu vou</button><button onClick={()=>void rsvp(item.id,"INTERESTED")}>Tenho interesse</button><a href={`/api/events/${item.id}/calendar.ics`} target="_blank" rel="noreferrer"><Download size={14}/> Calendario</a></div></div></article>)}{events.length===0&&<div className="empty-card">Nenhum evento agendado.</div>}</div>{showCreate&&<div className="overlay-sheet"><form className="sheet-card stack-form" onSubmit={create}><header><div><h3>Novo evento</h3><p>Planeje reunioes, lancamentos ou encontros.</p></div><button type="button" onClick={()=>setShowCreate(false)}><X/></button></header><label>Titulo<input name="title" required maxLength={120}/></label><label>Descricao<textarea name="description" rows={4} maxLength={1000}/></label><label>Local<input name="location" maxLength={240} placeholder="Sala de voz, escritorio, link..."/></label><div className="form-grid"><label>Inicio<input type="datetime-local" name="startsAt" required/></label><label>Fim<input type="datetime-local" name="endsAt"/></label></div><label>Capacidade<input type="number" name="capacity" min={1} placeholder="Sem limite"/></label><button className="primary-button">Criar evento</button></form></div>}</section>;
}
