[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ginga-sdk"
version = "2.1.0"
description = "SDK Python oficial para bots do Ginga Self-Hosted"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "aiohttp>=3.10,<4",
  "python-socketio[client]>=5.12,<6",
  "requests>=2.32,<3"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ginga*", "nexora*"]
