import { createHash, randomUUID } from "node:crypto";
import { readdir, stat } from "node:fs/promises";
import { join } from "node:path";
import { Router, raw } from "express";
import { z } from "zod";
import { prisma } from "../db.js";
import { asyncHandler, HttpError } from "../errors.js";
import { requireAuth } from "../middleware.js";
import { requireChannelCapability, requireGuildCapability, requireGuildMember, requireModerationTargetAny } from "../permissions.js";
import { requirePlatformAdmin } from "../platformAccess.js";
import { routeParam } from "../utils.js";
import { ensureV090Storage } from "../v090Storage.js";
import { GINGA_VERSION } from "../version.js";
import { reasonableGifDimensions, signatureMatches } from "../fileValidation.js";
import { requireModerationReasonIfConfigured } from "../v090Security.js";

export const v090Router = Router();
const color=z.string().regex(/^#[0-9a-fA-F]{6}$/);
const links=z.array(z.object({label:z.string().trim().min(1).max(24),url:z.string().url().max(500)})).max(5);
const secSchema=z.object({antiRaidEnabled:z.boolean(),joinWindowSeconds:z.number().int().min(10).max(600),joinLimit:z.number().int().min(2).max(100),quarantineEnabled:z.boolean(),quarantineMinutes:z.number().int().min(1).max(1440),newAccountHours:z.number().int().min(0).max(8760),blockExternalLinks:z.boolean(),blockInvites:z.boolean(),maxMentions:z.number().int().min(1).max(100),duplicateLimit:z.number().int().min(2).max(20),requireModerationReason:z.boolean(),autoTimeoutMinutes:z.number().int().min(0).max(10080),modLogChannelId:z.string().min(1).nullable()});
const profileSchema=z.object({bio:z.string().trim().max(280).nullable().optional(),pronouns:z.string().trim().max(40).nullable().optional(),accentColor:color.optional(),secondaryColor:color.optional(),profileTheme:z.enum(["AURORA","SOLID","MIDNIGHT"]).optional(),links:links.optional(),badgeText:z.string().trim().max(24).nullable().optional()}).refine(v=>Object.keys(v).length>0);
const socialSchema=z.object({birthday:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),avatarDecoration:z.enum(["NONE","RING","PIXEL","SPARK","WAVE"]).optional(),profileBadge:z.string().trim().max(24).nullable().optional(),statusExpiresAt:z.string().datetime().nullable().optional(),reducedMotion:z.boolean().optional(),compactProfile:z.boolean().optional()}).refine(v=>Object.keys(v).length>0);

function emit(req:any,guildId:string){req.app.get("io")?.to?.(`guild:${guildId}`)?.emit?.("guild:structure:changed",{guildId,at:new Date().toISOString(),source:"v0.4.1"});}
function assetUrl(kind:"emoji"|"sticker",guildId:string,id:string,etag:string){return `/api/guilds/${encodeURIComponent(guildId)}/${kind}s/${encodeURIComponent(id)}/${encodeURIComponent(etag)}`;}
async function dirSize(path:string):Promise<number>{let total=0;try{for(const e of await readdir(path,{withFileTypes:true})){const f=join(path,e.name);total+=e.isDirectory()?await dirSize(f):e.isFile()?(await stat(f)).size:0;}}catch{}return total;}

// Emojis/stickers
v090Router.get("/guilds/:guildId/emojis",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id,name,mime,etag,animated,created_at FROM "GingaGuildEmoji" WHERE guild_id=$1 ORDER BY LOWER(name)`,g);res.json({emojis:rows.map(r=>({id:r.id,name:r.name,mimeType:r.mime,animated:r.animated,url:assetUrl("emoji",g,r.id,r.etag),createdAt:r.created_at}))});}));
v090Router.post("/guilds/:guildId/emojis",requireAuth,raw({type:["image/png","image/webp","image/gif"],limit:"512kb"}),asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageServer");const name=z.string().trim().min(2).max(32).regex(/^[A-Za-z0-9_]+$/).parse(req.query.name);const body=req.body;if(!Buffer.isBuffer(body)||body.length<16)throw new HttpError(400,"Imagem invalida");const mime=String(req.headers["content-type"]||"").split(";")[0].toLowerCase();if(!["image/png","image/webp","image/gif"].includes(mime)||!signatureMatches(mime,body))throw new HttpError(415,"Imagem invalida");const id=randomUUID(),etag=createHash("sha256").update(body).digest("hex").slice(0,32);await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildEmoji"(id,guild_id,name,mime,asset,etag,animated,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,g,name,mime,body,etag,mime==="image/gif",req.auth!.sub);emit(req,g);res.status(201).json({emoji:{id,name,mimeType:mime,animated:mime==="image/gif",url:assetUrl("emoji",g,id,etag)}});}));
v090Router.get("/guilds/:guildId/emojis/:id/:etag",asyncHandler(async(req,res)=>{await ensureV090Storage();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT mime,asset,etag FROM "GingaGuildEmoji" WHERE guild_id=$1 AND id=$2 LIMIT 1`,routeParam(req.params.guildId,"guildId"),routeParam(req.params.id,"id"));const r=rows[0];if(!r||r.etag!==routeParam(req.params.etag,"etag"))throw new HttpError(404,"Emoji nao encontrado");res.setHeader("Content-Type",r.mime);res.setHeader("Cache-Control","public,max-age=31536000,immutable");res.send(Buffer.from(r.asset));}));
v090Router.delete("/guilds/:guildId/emojis/:id",requireAuth,asyncHandler(async(req,res)=>{const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageServer");await ensureV090Storage();await prisma.$executeRawUnsafe(`DELETE FROM "GingaGuildEmoji" WHERE guild_id=$1 AND id=$2`,g,routeParam(req.params.id,"id"));emit(req,g);res.status(204).end();}));

v090Router.get("/guilds/:guildId/stickers",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id,name,description,emoji,mime,etag,animated,created_at FROM "GingaGuildSticker" WHERE guild_id=$1 ORDER BY LOWER(name)`,g);res.json({stickers:rows.map(r=>({id:r.id,name:r.name,description:r.description,emoji:r.emoji,mimeType:r.mime,animated:r.animated,url:assetUrl("sticker",g,r.id,r.etag),createdAt:r.created_at}))});}));
v090Router.post("/guilds/:guildId/stickers",requireAuth,raw({type:["image/png","image/webp","image/gif"],limit:"1mb"}),asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageServer");const name=z.string().trim().min(2).max(40).parse(req.query.name),body=req.body;if(!Buffer.isBuffer(body)||body.length<16)throw new HttpError(400,"Sticker invalido");const mime=String(req.headers["content-type"]||"").split(";")[0].toLowerCase();if(!["image/png","image/webp","image/gif"].includes(mime)||!signatureMatches(mime,body))throw new HttpError(415,"Sticker invalido");const id=randomUUID(),etag=createHash("sha256").update(body).digest("hex").slice(0,32);await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildSticker"(id,guild_id,name,mime,asset,etag,animated,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,g,name,mime,body,etag,mime==="image/gif",req.auth!.sub);emit(req,g);res.status(201).json({sticker:{id,name,description:"",emoji:"",mimeType:mime,animated:mime==="image/gif",url:assetUrl("sticker",g,id,etag)}});}));
v090Router.get("/guilds/:guildId/stickers/:id/:etag",asyncHandler(async(req,res)=>{await ensureV090Storage();const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT mime,asset,etag FROM "GingaGuildSticker" WHERE guild_id=$1 AND id=$2 LIMIT 1`,routeParam(req.params.guildId,"guildId"),routeParam(req.params.id,"id"));const r=rows[0];if(!r||r.etag!==routeParam(req.params.etag,"etag"))throw new HttpError(404,"Sticker nao encontrado");res.setHeader("Content-Type",r.mime);res.setHeader("Cache-Control","public,max-age=31536000,immutable");res.send(Buffer.from(r.asset));}));
v090Router.delete("/guilds/:guildId/stickers/:id",requireAuth,asyncHandler(async(req,res)=>{const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageServer");await prisma.$executeRawUnsafe(`DELETE FROM "GingaGuildSticker" WHERE guild_id=$1 AND id=$2`,g,routeParam(req.params.id,"id"));emit(req,g);res.status(204).end();}));

// Areas + preferencias
v090Router.get("/guilds/:guildId/spaces",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const ss=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildSpace" WHERE guild_id=$1 ORDER BY position,created_at`,g),cats=await prisma.$queryRawUnsafe<any[]>(`SELECT sc.* FROM "GingaGuildSpaceCategory" sc JOIN "GingaGuildSpace" s ON s.id=sc.space_id WHERE s.guild_id=$1`,g),chs=await prisma.$queryRawUnsafe<any[]>(`SELECT sc.* FROM "GingaGuildSpaceChannel" sc JOIN "GingaGuildSpace" s ON s.id=sc.space_id WHERE s.guild_id=$1`,g);res.json({spaces:ss.map(s=>({id:s.id,guildId:s.guild_id,name:s.name,description:s.description,icon:s.icon,color:s.color,position:s.position,categoryIds:cats.filter(c=>c.space_id===s.id).map(c=>c.category_id),channelIds:chs.filter(c=>c.space_id===s.id).map(c=>c.channel_id)}))});}));
v090Router.post("/guilds/:guildId/spaces",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageChannels");const d=z.object({name:z.string().trim().min(1).max(48),description:z.string().max(160).default(""),icon:z.string().max(16).default(""),color:color.default("#7c3cff"),position:z.number().int().min(0).default(0)}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildSpace"(id,guild_id,name,description,icon,color,position) VALUES($1,$2,$3,$4,$5,$6,$7)`,id,g,d.name,d.description,d.icon,d.color,d.position);emit(req,g);res.status(201).json({space:{id,guildId:g,...d,categoryIds:[],channelIds:[]}});}));
v090Router.put("/spaces/:spaceId/content",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const id=routeParam(req.params.spaceId,"spaceId"),rows=await prisma.$queryRawUnsafe<any[]>(`SELECT guild_id FROM "GingaGuildSpace" WHERE id=$1`,id);if(!rows[0])throw new HttpError(404,"Area nao encontrada");const g=rows[0].guild_id;await requireGuildCapability(req.auth!.sub,g,"manageChannels");const d=z.object({categoryIds:z.array(z.string()).max(100),channelIds:z.array(z.string()).max(300)}).parse(req.body);await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`DELETE FROM "GingaGuildSpaceCategory" WHERE space_id=$1`,id);await tx.$executeRawUnsafe(`DELETE FROM "GingaGuildSpaceChannel" WHERE space_id=$1`,id);for(const c of [...new Set(d.categoryIds)])await tx.$executeRawUnsafe(`INSERT INTO "GingaGuildSpaceCategory"(space_id,category_id) VALUES($1,$2)`,id,c);for(const c of [...new Set(d.channelIds)])await tx.$executeRawUnsafe(`INSERT INTO "GingaGuildSpaceChannel"(space_id,channel_id) VALUES($1,$2)`,id,c);});emit(req,g);res.json(d);}));
v090Router.delete("/spaces/:spaceId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const id=routeParam(req.params.spaceId,"spaceId"),r=(await prisma.$queryRawUnsafe<any[]>(`SELECT guild_id FROM "GingaGuildSpace" WHERE id=$1`,id))[0];if(!r)throw new HttpError(404,"Area nao encontrada");await requireGuildCapability(req.auth!.sub,r.guild_id,"manageChannels");await prisma.$executeRawUnsafe(`DELETE FROM "GingaGuildSpace" WHERE id=$1`,id);emit(req,r.guild_id);res.status(204).end();}));
v090Router.get("/guilds/:guildId/channel-preferences",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT p.channel_id,p.favorite,p.hidden,p.updated_at FROM "GingaChannelPreference" p JOIN "Channel" c ON c.id=p.channel_id WHERE p.user_id=$1 AND c."guildId"=$2`,req.auth!.sub,g);res.json({preferences:rows.map(r=>({channelId:r.channel_id,favorite:r.favorite,hidden:r.hidden,updatedAt:r.updated_at}))});}));
v090Router.put("/channels/:channelId/preferences",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const c=routeParam(req.params.channelId,"channelId");await requireChannelCapability(req.auth!.sub,c,"view");const d=z.object({favorite:z.boolean(),hidden:z.boolean()}).parse(req.body);await prisma.$executeRawUnsafe(`INSERT INTO "GingaChannelPreference"(user_id,channel_id,favorite,hidden,updated_at) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(user_id,channel_id) DO UPDATE SET favorite=$3,hidden=$4,updated_at=NOW()`,req.auth!.sub,c,d.favorite,d.hidden);res.json({preference:{channelId:c,...d}});}));

// Perfil social/per-server/notas/mutuals
function purl(kind:string,g:string,u:string,e:string|null){return e?`/api/guilds/${g}/member-profiles/${u}/${kind}/${e}`:null;}
function serializeP(r:any){return r?{guildId:r.guild_id,userId:r.user_id,bio:r.bio,pronouns:r.pronouns,accentColor:r.accent_color,secondaryColor:r.secondary_color,profileTheme:r.profile_theme,links:Array.isArray(r.links)?r.links:[],avatarUrl:purl("avatar",r.guild_id,r.user_id,r.avatar_etag),bannerUrl:purl("banner",r.guild_id,r.user_id,r.banner_etag),badgeText:r.badge_text,updatedAt:r.updated_at}:null;}
v090Router.get("/guilds/:guildId/member-profiles/:userId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),u=routeParam(req.params.userId,"userId");await Promise.all([requireGuildMember(req.auth!.sub,g),requireGuildMember(u,g)]);const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildMemberProfile" WHERE guild_id=$1 AND user_id=$2`,g,u))[0];res.json({profile:serializeP(r)});}));
v090Router.patch("/guilds/:guildId/member-profile/me",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),u=req.auth!.sub,d=profileSchema.parse(req.body);await requireGuildMember(u,g);const old=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildMemberProfile" WHERE guild_id=$1 AND user_id=$2`,g,u))[0]||{};await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildMemberProfile"(guild_id,user_id,bio,pronouns,accent_color,secondary_color,profile_theme,links,badge_text,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,NOW()) ON CONFLICT(guild_id,user_id) DO UPDATE SET bio=$3,pronouns=$4,accent_color=$5,secondary_color=$6,profile_theme=$7,links=$8::jsonb,badge_text=$9,updated_at=NOW()`,g,u,d.bio??old.bio??null,d.pronouns??old.pronouns??null,d.accentColor??old.accent_color??"#7c3cff",d.secondaryColor??old.secondary_color??"#2c74ff",d.profileTheme??old.profile_theme??"AURORA",JSON.stringify(d.links??old.links??[]),d.badgeText??old.badge_text??null);res.json({profile:serializeP((await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildMemberProfile" WHERE guild_id=$1 AND user_id=$2`,g,u))[0])});}));
for(const kind of ["avatar","banner"] as const){v090Router.post(`/guilds/:guildId/member-profile/${kind}`,requireAuth,raw({type:["image/webp","image/gif"],limit:kind==="avatar"?"8mb":"12mb"}),asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),u=req.auth!.sub;await requireGuildMember(u,g);const body=req.body,mime=String(req.headers["content-type"]||"").split(";")[0].toLowerCase();if(!Buffer.isBuffer(body)||!["image/webp","image/gif"].includes(mime)||!signatureMatches(mime,body))throw new HttpError(415,"Imagem invalida. Use WebP ou GIF");if(mime==="image/gif"&&!reasonableGifDimensions(body))throw new HttpError(415,"GIF invalido ou com resolucao grande demais");const max=kind==="avatar"?8*1024*1024:12*1024*1024;if(body.length>max)throw new HttpError(413,kind==="avatar"?"Avatar muito grande. Limite: 8 MB":"Banner muito grande. Limite: 12 MB");const etag=createHash("sha256").update(body).digest("hex").slice(0,32),a=kind==="avatar"?"avatar_asset":"banner_asset",m=kind==="avatar"?"avatar_mime":"banner_mime",e=kind==="avatar"?"avatar_etag":"banner_etag";await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildMemberProfile"(guild_id,user_id,${a},${m},${e},updated_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT(guild_id,user_id) DO UPDATE SET ${a}=$3,${m}=$4,${e}=$5,updated_at=NOW()`,g,u,body,mime,etag);res.json({url:purl(kind,g,u,etag)});}));v090Router.get(`/guilds/:guildId/member-profiles/:userId/${kind}/:etag`,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),u=routeParam(req.params.userId,"userId"),etag=routeParam(req.params.etag,"etag"),a=kind==="avatar"?"avatar_asset":"banner_asset",m=kind==="avatar"?"avatar_mime":"banner_mime",e=kind==="avatar"?"avatar_etag":"banner_etag",r=(await prisma.$queryRawUnsafe<any[]>(`SELECT ${a} asset,${m} mime,${e} etag FROM "GingaGuildMemberProfile" WHERE guild_id=$1 AND user_id=$2`,g,u))[0];if(!r?.asset||r.etag!==etag)throw new HttpError(404,"Imagem nao encontrada");res.setHeader("Content-Type",r.mime||"image/webp");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Content-Disposition","inline");res.setHeader("Cache-Control","public,max-age=31536000,immutable");res.send(Buffer.from(r.asset));}));}

v090Router.get("/social-profile/me",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaUserSocialProfile" WHERE user_id=$1`,req.auth!.sub))[0];res.json({profile:r?{birthday:r.birthday?.toISOString?.().slice(0,10)??null,avatarDecoration:r.avatar_decoration,profileBadge:r.profile_badge,statusExpiresAt:r.status_expires_at,reducedMotion:r.reduced_motion,compactProfile:r.compact_profile,updatedAt:r.updated_at}:{birthday:null,avatarDecoration:"NONE",profileBadge:null,statusExpiresAt:null,reducedMotion:false,compactProfile:false,updatedAt:null}});}));
v090Router.patch("/social-profile/me",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const d=socialSchema.parse(req.body),u=req.auth!.sub,old=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaUserSocialProfile" WHERE user_id=$1`,u))[0]||{};await prisma.$executeRawUnsafe(`INSERT INTO "GingaUserSocialProfile"(user_id,birthday,avatar_decoration,profile_badge,status_expires_at,reduced_motion,compact_profile,updated_at) VALUES($1,$2::date,$3,$4,$5::timestamptz,$6,$7,NOW()) ON CONFLICT(user_id) DO UPDATE SET birthday=$2::date,avatar_decoration=$3,profile_badge=$4,status_expires_at=$5::timestamptz,reduced_motion=$6,compact_profile=$7,updated_at=NOW()`,u,d.birthday??(old.birthday?.toISOString?.().slice(0,10)??null),d.avatarDecoration??old.avatar_decoration??"NONE",d.profileBadge??old.profile_badge??null,d.statusExpiresAt??old.status_expires_at?.toISOString?.()??null,d.reducedMotion??old.reduced_motion??false,d.compactProfile??old.compact_profile??false);res.json({ok:true});}));
v090Router.get("/users/:userId/note",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const u=routeParam(req.params.userId,"userId"),r=(await prisma.$queryRawUnsafe<any[]>(`SELECT note,updated_at FROM "GingaUserNote" WHERE owner_user_id=$1 AND target_user_id=$2`,req.auth!.sub,u))[0];res.json({note:r?.note??"",updatedAt:r?.updated_at??null});}));
v090Router.put("/users/:userId/note",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const u=routeParam(req.params.userId,"userId"),note=z.string().trim().max(1000).parse(req.body?.note??"");if(!note)await prisma.$executeRawUnsafe(`DELETE FROM "GingaUserNote" WHERE owner_user_id=$1 AND target_user_id=$2`,req.auth!.sub,u);else await prisma.$executeRawUnsafe(`INSERT INTO "GingaUserNote"(owner_user_id,target_user_id,note,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(owner_user_id,target_user_id) DO UPDATE SET note=$3,updated_at=NOW()`,req.auth!.sub,u,note);res.json({note});}));
v090Router.get("/users/:userId/mutuals",requireAuth,asyncHandler(async(req,res)=>{const u=routeParam(req.params.userId,"userId"),me=req.auth!.sub;if(u===me)return res.json({friends:[],guilds:[]});const guilds=await prisma.guild.findMany({where:{members:{some:{userId:me}},AND:{members:{some:{userId:u}}}},select:{id:true,name:true,iconColor:true},take:100});res.json({friends:[],guilds});}));

// Onboarding
async function onboarding(g:string){const qs=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaOnboardingQuestion" WHERE guild_id=$1 ORDER BY position,created_at`,g),ids=qs.map(q=>q.id),os=ids.length?await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaOnboardingOption" WHERE question_id=ANY($1::text[]) ORDER BY position,created_at`,ids):[];return qs.map(q=>({id:q.id,title:q.title,description:q.description,multiple:q.multiple,required:q.required,enabled:q.enabled,position:q.position,options:os.filter(o=>o.question_id===q.id).map(o=>({id:o.id,label:o.label,description:o.description,emoji:o.emoji,roleId:o.role_id,channelIds:o.channel_ids,position:o.position}))}));}
v090Router.get("/guilds/:guildId/onboarding",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);res.json({questions:await onboarding(g)});}));
v090Router.post("/guilds/:guildId/onboarding/questions",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageServer");const d=z.object({title:z.string().trim().min(2).max(120),description:z.string().max(240).default(""),multiple:z.boolean().default(false),required:z.boolean().default(true),enabled:z.boolean().default(true),position:z.number().int().default(0)}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaOnboardingQuestion"(id,guild_id,title,description,multiple,required,enabled,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,g,d.title,d.description,d.multiple,d.required,d.enabled,d.position);res.status(201).json({question:{id,...d,options:[]}});}));
v090Router.post("/onboarding/questions/:questionId/options",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const q=routeParam(req.params.questionId,"questionId"),qr=(await prisma.$queryRawUnsafe<any[]>(`SELECT guild_id FROM "GingaOnboardingQuestion" WHERE id=$1`,q))[0];if(!qr)throw new HttpError(404,"Pergunta nao encontrada");await requireGuildCapability(req.auth!.sub,qr.guild_id,"manageServer");const d=z.object({label:z.string().min(1).max(80),description:z.string().max(160).default(""),emoji:z.string().max(16).default(""),roleId:z.string().nullable().default(null),channelIds:z.array(z.string()).default([]),position:z.number().int().default(0)}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaOnboardingOption"(id,question_id,label,description,emoji,role_id,channel_ids,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,id,q,d.label,d.description,d.emoji,d.roleId,d.channelIds,d.position);res.status(201).json({option:{id,...d}});}));
// CRUD administrativo do onboarding. O Electron nao depende mais de dialogs nativos e o painel pode desfazer o que criou.
v090Router.delete("/onboarding/questions/:questionId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const q=routeParam(req.params.questionId,"questionId"),row=(await prisma.$queryRawUnsafe<any[]>(`SELECT guild_id FROM "GingaOnboardingQuestion" WHERE id=$1`,q))[0];if(!row)throw new HttpError(404,"Pergunta nao encontrada");await requireGuildCapability(req.auth!.sub,row.guild_id,"manageServer");await prisma.$executeRawUnsafe(`DELETE FROM "GingaOnboardingQuestion" WHERE id=$1`,q);emit(req,row.guild_id);res.status(204).end();}));
v090Router.delete("/onboarding/questions/:questionId/options/:optionId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const q=routeParam(req.params.questionId,"questionId"),o=routeParam(req.params.optionId,"optionId"),row=(await prisma.$queryRawUnsafe<any[]>(`SELECT guild_id FROM "GingaOnboardingQuestion" WHERE id=$1`,q))[0];if(!row)throw new HttpError(404,"Pergunta nao encontrada");await requireGuildCapability(req.auth!.sub,row.guild_id,"manageServer");await prisma.$executeRawUnsafe(`DELETE FROM "GingaOnboardingOption" WHERE id=$1 AND question_id=$2`,o,q);emit(req,row.guild_id);res.status(204).end();}));
v090Router.get("/guilds/:guildId/onboarding/me",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT answers,completed_at,updated_at FROM "GingaOnboardingProgress" WHERE guild_id=$1 AND user_id=$2`,g,req.auth!.sub))[0];res.json({progress:r??{answers:{},completed_at:null,updated_at:null}});}));
v090Router.put("/guilds/:guildId/onboarding/me",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),answers=z.record(z.string(),z.array(z.string())).parse(req.body?.answers??{});await requireGuildMember(req.auth!.sub,g);const qs=await onboarding(g),roles=new Set<string>(),channels=new Set<string>();for(const q of qs.filter(q=>q.enabled)){const ids=answers[q.id]??[];if(q.required&&!ids.length)throw new HttpError(400,`Responda: ${q.title}`);for(const id of ids){const o=q.options.find((x:any)=>x.id===id);if(!o)throw new HttpError(400,"Opcao invalida");if(o.roleId)roles.add(o.roleId);for(const c of o.channelIds)channels.add(c);}}await prisma.$transaction(async tx=>{for(const roleId of roles)await tx.guildMemberCustomRole.upsert({where:{guildId_userId_roleId:{guildId:g,userId:req.auth!.sub,roleId}},update:{},create:{guildId:g,userId:req.auth!.sub,roleId}});for(const c of channels)await tx.$executeRawUnsafe(`INSERT INTO "GingaChannelPreference"(user_id,channel_id,favorite,hidden,updated_at) VALUES($1,$2,TRUE,FALSE,NOW()) ON CONFLICT(user_id,channel_id) DO UPDATE SET favorite=TRUE,hidden=FALSE,updated_at=NOW()`,req.auth!.sub,c);await tx.$executeRawUnsafe(`INSERT INTO "GingaOnboardingProgress"(guild_id,user_id,answers,completed_at,updated_at) VALUES($1,$2,$3::jsonb,NOW(),NOW()) ON CONFLICT(guild_id,user_id) DO UPDATE SET answers=$3::jsonb,completed_at=NOW(),updated_at=NOW()`,g,req.auth!.sub,JSON.stringify(answers));});res.json({completed:true,answers,favoriteChannelIds:[...channels]});}));

// Seguranca, voz dinamica, badges
function serializeSec(r:any){return {antiRaidEnabled:r?.anti_raid_enabled??false,joinWindowSeconds:r?.join_window_seconds??30,joinLimit:r?.join_limit??8,quarantineEnabled:r?.quarantine_enabled??false,quarantineMinutes:r?.quarantine_minutes??10,newAccountHours:r?.new_account_hours??24,blockExternalLinks:r?.block_external_links??false,blockInvites:r?.block_invites??false,maxMentions:r?.max_mentions??8,duplicateLimit:r?.duplicate_limit??5,requireModerationReason:r?.require_moderation_reason??false,autoTimeoutMinutes:r?.auto_timeout_minutes??0,modLogChannelId:r?.mod_log_channel_id??null};}
v090Router.get("/guilds/:guildId/security-policy",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageAutoMod");res.json({policy:serializeSec((await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildSecurityPolicy" WHERE guild_id=$1`,g))[0])});}));
v090Router.put("/guilds/:guildId/security-policy",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),d=secSchema.parse(req.body);await requireGuildCapability(req.auth!.sub,g,"manageAutoMod");await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildSecurityPolicy"(guild_id,anti_raid_enabled,join_window_seconds,join_limit,quarantine_enabled,quarantine_minutes,new_account_hours,block_external_links,block_invites,max_mentions,duplicate_limit,require_moderation_reason,auto_timeout_minutes,mod_log_channel_id,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW()) ON CONFLICT(guild_id) DO UPDATE SET anti_raid_enabled=$2,join_window_seconds=$3,join_limit=$4,quarantine_enabled=$5,quarantine_minutes=$6,new_account_hours=$7,block_external_links=$8,block_invites=$9,max_mentions=$10,duplicate_limit=$11,require_moderation_reason=$12,auto_timeout_minutes=$13,mod_log_channel_id=$14,updated_at=NOW()`,g,d.antiRaidEnabled,d.joinWindowSeconds,d.joinLimit,d.quarantineEnabled,d.quarantineMinutes,d.newAccountHours,d.blockExternalLinks,d.blockInvites,d.maxMentions,d.duplicateLimit,d.requireModerationReason,d.autoTimeoutMinutes,d.modLogChannelId);res.json({policy:d});}));
v090Router.post("/guilds/:guildId/members/:userId/soft-ban",requireAuth,asyncHandler(async(req,res)=>{const g=routeParam(req.params.guildId,"guildId"),u=routeParam(req.params.userId,"userId"),d=z.object({reason:z.string().trim().max(500).default(""),deleteMessageMinutes:z.number().int().min(0).max(10080).default(60)}).parse(req.body);await requireModerationTargetAny(req.auth!.sub,g,u,["banMembers"]);await requireModerationReasonIfConfigured(g,d.reason);const since=new Date(Date.now()-d.deleteMessageMinutes*60000);await prisma.$transaction(async tx=>{if(d.deleteMessageMinutes)await tx.message.deleteMany({where:{authorId:u,channel:{guildId:g},createdAt:{gte:since}}});await tx.guildMemberCustomRole.deleteMany({where:{guildId:g,userId:u}});await tx.guildMember.deleteMany({where:{guildId:g,userId:u}});await tx.guildBan.deleteMany({where:{guildId:g,userId:u}});});emit(req,g);res.json({ok:true});}));

v090Router.get("/guilds/:guildId/dynamic-voice/templates",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaDynamicVoiceTemplate" WHERE guild_id=$1 ORDER BY position,created_at`,g);res.json({templates:rows.map(r=>({id:r.id,guildId:r.guild_id,name:r.name,namePattern:r.name_pattern,categoryId:r.category_id,userLimit:r.user_limit,ownerControls:r.owner_controls,autoDelete:r.auto_delete,enabled:r.enabled,position:r.position}))});}));
v090Router.post("/guilds/:guildId/dynamic-voice/templates",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageChannels");const d=z.object({name:z.string().trim().min(1).max(48),namePattern:z.string().trim().min(1).max(48).default("Sala de {user}"),categoryId:z.string().nullable().default(null),userLimit:z.number().int().min(0).max(99).default(0),ownerControls:z.boolean().default(true),autoDelete:z.boolean().default(true),enabled:z.boolean().default(true),position:z.number().int().default(0)}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaDynamicVoiceTemplate"(id,guild_id,name,name_pattern,category_id,user_limit,owner_controls,auto_delete,enabled,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,id,g,d.name,d.namePattern,d.categoryId,d.userLimit,d.ownerControls,d.autoDelete,d.enabled,d.position);res.status(201).json({template:{id,guildId:g,...d}});}));
v090Router.delete("/guilds/:guildId/dynamic-voice/templates/:templateId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),t=routeParam(req.params.templateId,"templateId");await requireGuildCapability(req.auth!.sub,g,"manageChannels");const found=(await prisma.$queryRawUnsafe<any[]>(`SELECT id FROM "GingaDynamicVoiceTemplate" WHERE id=$1 AND guild_id=$2`,t,g))[0];if(!found)throw new HttpError(404,"Modelo nao encontrado");await prisma.$executeRawUnsafe(`DELETE FROM "GingaDynamicVoiceTemplate" WHERE id=$1 AND guild_id=$2`,t,g);emit(req,g);res.status(204).end();}));
v090Router.post("/guilds/:guildId/dynamic-voice/:templateId/create",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),t=routeParam(req.params.templateId,"templateId");await requireGuildMember(req.auth!.sub,g);const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaDynamicVoiceTemplate" WHERE id=$1 AND guild_id=$2 AND enabled=TRUE`,t,g))[0];if(!r)throw new HttpError(404,"Modelo indisponivel");const user=await prisma.user.findUniqueOrThrow({where:{id:req.auth!.sub},select:{displayName:true,username:true}}),name=r.name_pattern.replace(/\{user\}/gi,user.displayName||user.username).slice(0,48),last=await prisma.channel.aggregate({where:{guildId:g,categoryId:r.category_id},_max:{position:true}}),channel=await prisma.channel.create({data:{guildId:g,categoryId:r.category_id,name,type:"VOICE",position:(last._max.position??-1)+1,syncPermissionsWithCategory:Boolean(r.category_id),permissions:{create:[{role:"MODERATOR",canView:true,canSendMessages:true,canConnect:true},{role:"MEMBER",canView:true,canSendMessages:true,canConnect:true}]}}});await prisma.$executeRawUnsafe(`INSERT INTO "GingaDynamicVoiceRoom"(channel_id,template_id,owner_user_id,user_limit) VALUES($1,$2,$3,$4)`,channel.id,t,req.auth!.sub,r.user_limit);emit(req,g);res.status(201).json({channel,room:{ownerUserId:req.auth!.sub,userLimit:r.user_limit,locked:false}});}));

v090Router.get("/guilds/:guildId/badges",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildMember(req.auth!.sub,g);const b=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaGuildBadge" WHERE guild_id=$1`,g),ids=b.map(x=>x.id),a=ids.length?await prisma.$queryRawUnsafe<any[]>(`SELECT badge_id,user_id FROM "GingaGuildBadgeAssignment" WHERE badge_id=ANY($1::text[])`,ids):[];res.json({badges:b.map(x=>({id:x.id,name:x.name,icon:x.icon,color:x.color,description:x.description,userIds:a.filter(y=>y.badge_id===x.id).map(y=>y.user_id)}))});}));
v090Router.post("/guilds/:guildId/badges",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageRoles");const d=z.object({name:z.string().min(1).max(32),icon:z.string().max(16).default(""),color:color.default("#7c3cff"),description:z.string().max(120).default("")}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildBadge"(id,guild_id,name,icon,color,description) VALUES($1,$2,$3,$4,$5,$6)`,id,g,d.name,d.icon,d.color,d.description);res.status(201).json({badge:{id,...d,userIds:[]}});}));
v090Router.put("/guilds/:guildId/badges/:badgeId/members/:userId",requireAuth,asyncHandler(async(req,res)=>{const g=routeParam(req.params.guildId,"guildId");await requireGuildCapability(req.auth!.sub,g,"manageRoles");await prisma.$executeRawUnsafe(`INSERT INTO "GingaGuildBadgeAssignment"(badge_id,user_id,assigned_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,routeParam(req.params.badgeId,"badgeId"),routeParam(req.params.userId,"userId"),req.auth!.sub);res.status(204).end();}));
v090Router.delete("/guilds/:guildId/badges/:badgeId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),b=routeParam(req.params.badgeId,"badgeId");await requireGuildCapability(req.auth!.sub,g,"manageRoles");const found=(await prisma.$queryRawUnsafe<any[]>(`SELECT id FROM "GingaGuildBadge" WHERE id=$1 AND guild_id=$2`,b,g))[0];if(!found)throw new HttpError(404,"Badge nao encontrada");await prisma.$executeRawUnsafe(`DELETE FROM "GingaGuildBadge" WHERE id=$1 AND guild_id=$2`,b,g);emit(req,g);res.status(204).end();}));
v090Router.delete("/guilds/:guildId/badges/:badgeId/members/:userId",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const g=routeParam(req.params.guildId,"guildId"),b=routeParam(req.params.badgeId,"badgeId"),u=routeParam(req.params.userId,"userId");await requireGuildCapability(req.auth!.sub,g,"manageRoles");const found=(await prisma.$queryRawUnsafe<any[]>(`SELECT id FROM "GingaGuildBadge" WHERE id=$1 AND guild_id=$2`,b,g))[0];if(!found)throw new HttpError(404,"Badge nao encontrada");await prisma.$executeRawUnsafe(`DELETE FROM "GingaGuildBadgeAssignment" WHERE badge_id=$1 AND user_id=$2`,b,u);emit(req,g);res.status(204).end();}));

// Drafts + history + desktop/admin
v090Router.get("/channels/:channelId/draft",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const c=routeParam(req.params.channelId,"channelId");await requireChannelCapability(req.auth!.sub,c,"view");const r=(await prisma.$queryRawUnsafe<any[]>(`SELECT content,updated_at FROM "GingaDraft" WHERE user_id=$1 AND channel_id=$2`,req.auth!.sub,c))[0];res.json({draft:r?{content:r.content,updatedAt:r.updated_at}:null});}));
v090Router.put("/channels/:channelId/draft",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const c=routeParam(req.params.channelId,"channelId"),content=z.string().max(8000).parse(req.body?.content??"");await requireChannelCapability(req.auth!.sub,c,"view");if(!content)await prisma.$executeRawUnsafe(`DELETE FROM "GingaDraft" WHERE user_id=$1 AND channel_id=$2`,req.auth!.sub,c);else await prisma.$executeRawUnsafe(`INSERT INTO "GingaDraft"(user_id,channel_id,content,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(user_id,channel_id) DO UPDATE SET content=$3,updated_at=NOW()`,req.auth!.sub,c,content);res.json({draft:content?{content,updatedAt:new Date()}:null});}));
v090Router.get("/messages/:messageId/edit-history",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const id=routeParam(req.params.messageId,"messageId"),m=await prisma.message.findUnique({where:{id},select:{channelId:true}});if(!m)throw new HttpError(404,"Mensagem nao encontrada");await requireChannelCapability(req.auth!.sub,m.channelId,"view");const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT id,editor_id,previous_content,edited_at FROM "GingaMessageEditHistory" WHERE message_id=$1 ORDER BY edited_at DESC LIMIT 50`,id);res.json({history:rows.map(r=>({id:r.id,editorId:r.editor_id,previousContent:r.previous_content,editedAt:r.edited_at}))});}));
v090Router.get("/client/compatibility",requireAuth,asyncHandler(async(req,res)=>{const v=z.string().max(32).default("").parse(req.query.version??""),a=GINGA_VERSION.split(".").slice(0,2).join("."),b=v.split(".").slice(0,2).join(".");res.json({serverVersion:GINGA_VERSION,clientVersion:v,compatible:!v||a===b,recommendedVersion:GINGA_VERSION,minimumDesktopVersion:"0.4.0"});}));
v090Router.post("/client/crash-reports",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();const d=z.object({version:z.string().max(32),platform:z.string().max(64).default(""),kind:z.string().max(32).default("renderer"),message:z.string().min(1).max(1000),stack:z.string().max(12000).default(""),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body),id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "GingaClientCrashReport"(id,user_id,version,platform,kind,message,stack,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,id,req.auth!.sub,d.version,d.platform,d.kind,d.message,d.stack,JSON.stringify(d.metadata));res.status(201).json({id});}));
v090Router.get("/platform/admin/crash-reports",requireAuth,asyncHandler(async(req,res)=>{await ensureV090Storage();await requirePlatformAdmin(req.auth!.sub);res.json({reports:await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "GingaClientCrashReport" ORDER BY created_at DESC LIMIT 100`)});}));
v090Router.get("/platform/admin/health-v2",requireAuth,asyncHandler(async(req,res)=>{await requirePlatformAdmin(req.auth!.sub);const [users,guilds,channels,messages,uploads,database]=await Promise.all([prisma.user.count({where:{accountType:"HUMAN"}}),prisma.guild.count(),prisma.channel.count(),prisma.message.count(),dirSize(process.env.UPLOAD_DIR||"/data/uploads"),prisma.$queryRawUnsafe<any[]>(`SELECT pg_size_pretty(pg_database_size(current_database())) size`).catch(()=>[{size:"indisponivel"}])]);const m=process.memoryUsage();res.json({version:GINGA_VERSION,process:{uptimeSeconds:Math.round(process.uptime()),rssBytes:m.rss,heapUsedBytes:m.heapUsed,node:process.version},counts:{users,guilds,channels,messages},storage:{uploadsBytes:uploads,database:database[0]?.size??"indisponivel"},now:new Date().toISOString()});}));
