export type GuildNotificationLevel = "DEFAULT" | "MENTIONS" | "NONE";
export type GuildNotificationMode = "ALL" | "MENTIONS" | "SILENT";
export interface GuildLocalPreferences {
  muted: boolean;
  notificationLevel: GuildNotificationLevel;
  hideMutedChannels: boolean;
  mutedChannelIds: string[];
  mutedChannels: Record<string, number | null>;
  muteUntil: number | null;
}
const STORAGE_KEY = "ginga.guildPreferences.v2";
const LEGACY_STORAGE_KEY = "ginga.guildPreferences.v1";
export const GUILD_PREFERENCES_EVENT = "ginga:guild-preferences";
const DEFAULTS: GuildLocalPreferences = { muted:false, notificationLevel:"DEFAULT", hideMutedChannels:false, mutedChannelIds:[], mutedChannels:{}, muteUntil:null };
function activeUntil(value: unknown): number | null { const numeric=Number(value); return Number.isFinite(numeric)&&numeric>Date.now()?numeric:null; }
function normalizeChannelMutes(value: unknown, legacyIds: string[]) { const result:Record<string,number|null>={}; if(value&&typeof value==="object"&&!Array.isArray(value)){for(const [id,raw] of Object.entries(value as Record<string,unknown>)){if(!id)continue;if(raw===null)result[id]=null;else{const until=activeUntil(raw);if(until)result[id]=until;}}} for(const id of legacyIds)if(id&&!(id in result))result[id]=null; return result; }
function readRaw():Record<string,Partial<GuildLocalPreferences>>{try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_STORAGE_KEY);if(!raw)return{};const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:{}}catch{return{}}}
function readAll(){const parsed=readRaw();const result:Record<string,GuildLocalPreferences>={};for(const [guildId,value] of Object.entries(parsed)){if(!guildId||!value||typeof value!=="object")continue;const notificationLevel=value.notificationLevel==="MENTIONS"||value.notificationLevel==="NONE"?value.notificationLevel:"DEFAULT";const legacyIds=Array.isArray(value.mutedChannelIds)?value.mutedChannelIds.filter((id):id is string=>typeof id==="string"&&id.length>0):[];const mutedChannels=normalizeChannelMutes(value.mutedChannels,legacyIds);const muted=Boolean(value.muted)||notificationLevel==="NONE";result[guildId]={muted,notificationLevel:muted?"NONE":notificationLevel,hideMutedChannels:Boolean(value.hideMutedChannels),mutedChannelIds:Object.keys(mutedChannels),mutedChannels,muteUntil:activeUntil(value.muteUntil)};}return result;}
function persist(all:Record<string,GuildLocalPreferences>){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(all));localStorage.removeItem(LEGACY_STORAGE_KEY)}catch{}}
export function loadGuildPreferences(guildId:string):GuildLocalPreferences{if(!guildId)return{...DEFAULTS,mutedChannelIds:[],mutedChannels:{}};const all=readAll();const value=all[guildId];if(!value)return{...DEFAULTS,mutedChannelIds:[],mutedChannels:{}};const mutedChannels=normalizeChannelMutes(value.mutedChannels,[]);const next={...value,muteUntil:activeUntil(value.muteUntil),mutedChannels,mutedChannelIds:Object.keys(mutedChannels)};all[guildId]=next;persist(all);return next;}
export function guildNotificationMode(p:GuildLocalPreferences):GuildNotificationMode{if(p.muted||p.notificationLevel==="NONE"||Boolean(p.muteUntil&&p.muteUntil>Date.now()))return"SILENT";if(p.notificationLevel==="MENTIONS")return"MENTIONS";return"ALL";}
export function isGuildSilent(p:GuildLocalPreferences){return guildNotificationMode(p)==="SILENT";}
export function isChannelMuted(p:GuildLocalPreferences,channelId:string){if(!channelId)return false;if(Object.prototype.hasOwnProperty.call(p.mutedChannels,channelId)){const until=p.mutedChannels[channelId];return until===null||until>Date.now();}return p.mutedChannelIds.includes(channelId);}
export function guildAllowsMessageActivity(p:GuildLocalPreferences,mention:boolean,channelId?:string){if(channelId&&isChannelMuted(p,channelId))return false;const mode=guildNotificationMode(p);return mode==="SILENT"?false:mode==="MENTIONS"?mention:true;}
export function updateGuildPreferences(guildId:string,patch:Partial<GuildLocalPreferences>){const all=readAll();const current=loadGuildPreferences(guildId);const next:GuildLocalPreferences={...current,...patch,mutedChannels:patch.mutedChannels?normalizeChannelMutes(patch.mutedChannels,[]):{...current.mutedChannels},mutedChannelIds:[]};if(patch.mutedChannelIds&&!patch.mutedChannels)next.mutedChannels=normalizeChannelMutes({},patch.mutedChannelIds);next.mutedChannelIds=Object.keys(next.mutedChannels);if(patch.notificationLevel==="NONE")next.muted=true;if(patch.notificationLevel==="DEFAULT"||patch.notificationLevel==="MENTIONS")next.muted=false;if(patch.muted===true)next.notificationLevel="NONE";if(patch.muted===false&&next.notificationLevel==="NONE"&&patch.notificationLevel===undefined)next.notificationLevel="DEFAULT";if(patch.muteUntil!==undefined)next.muteUntil=activeUntil(patch.muteUntil);all[guildId]=next;persist(all);window.dispatchEvent(new CustomEvent(GUILD_PREFERENCES_EVENT,{detail:{guildId,preferences:next}}));return next;}
export function setGuildNotificationMode(guildId:string,mode:GuildNotificationMode){if(mode==="SILENT")return updateGuildPreferences(guildId,{muted:true,notificationLevel:"NONE",muteUntil:null});if(mode==="MENTIONS")return updateGuildPreferences(guildId,{muted:false,notificationLevel:"MENTIONS",muteUntil:null});return updateGuildPreferences(guildId,{muted:false,notificationLevel:"DEFAULT",muteUntil:null});}
export function muteGuildFor(guildId:string,durationMs:number|null){if(durationMs===null)return setGuildNotificationMode(guildId,"SILENT");const current=loadGuildPreferences(guildId);const patch:Partial<GuildLocalPreferences>={muteUntil:Date.now()+Math.max(60000,durationMs)};if(current.muted||current.notificationLevel==="NONE"){patch.muted=false;patch.notificationLevel="DEFAULT";}return updateGuildPreferences(guildId,patch);}
export function unmuteGuild(guildId:string){const current=loadGuildPreferences(guildId);if(current.muted||current.notificationLevel==="NONE")return setGuildNotificationMode(guildId,"ALL");return updateGuildPreferences(guildId,{muteUntil:null});}
export function muteChannelFor(guildId:string,channelId:string,durationMs:number|null){const current=loadGuildPreferences(guildId);return updateGuildPreferences(guildId,{mutedChannels:{...current.mutedChannels,[channelId]:durationMs===null?null:Date.now()+Math.max(60000,durationMs)}});}
export function unmuteChannel(guildId:string,channelId:string){const current=loadGuildPreferences(guildId);const mutedChannels={...current.mutedChannels};delete mutedChannels[channelId];return updateGuildPreferences(guildId,{mutedChannels});}
export function toggleMutedChannel(guildId:string,channelId:string){const current=loadGuildPreferences(guildId);return isChannelMuted(current,channelId)?unmuteChannel(guildId,channelId):muteChannelFor(guildId,channelId,null);}
